services:
  postgres-auth:
    image: postgres:16
    container_name: nutriwise-postgres-auth
    environment:
      POSTGRES_DB: nutriwise_auth
      POSTGRES_USER: nutriwise
      POSTGRES_PASSWORD: nutriwise
    ports:
      - "5433:5432"
    volumes:
      - pg_auth_data:/var/lib/postgresql/data

  postgres-profile:
    image: postgres:16
    container_name: nutriwise-postgres-profile
    environment:
      POSTGRES_DB: nutriwise_profile
      POSTGRES_USER: nutriwise
      POSTGRES_PASSWORD: nutriwise
    ports:
      - "5434:5432"
    volumes:
      - pg_profile_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: nutriwise-redis
    ports:
      - "6379:6379"

  kafka:
    image: bitnami/kafka:3.7
    container_name: nutriwise-kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_CFG_NODE_ID: 1
      KAFKA_CFG_PROCESS_ROLES: broker,controller
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      ALLOW_PLAINTEXT_LISTENER: "yes"
    volumes:
      - kafka_data:/bitnami/kafka

volumes:
  pg_auth_data:
  pg_profile_data:
  kafka_data:
