services:
  postgres-auth:
    image: postgres:16
    container_name: nutriwise-postgres-auth
    environment:
      POSTGRES_DB: nutriwise_auth
      POSTGRES_USER: nutriwise
      POSTGRES_PASSWORD: nutriwise
    ports:
      - "5433:5432"
    volumes:
      - pg_auth_data:/var/lib/postgresql/data

  postgres-profile:
    image: postgres:16
    container_name: nutriwise-postgres-profile
    environment:
      POSTGRES_DB: nutriwise_profile
      POSTGRES_USER: nutriwise
      POSTGRES_PASSWORD: nutriwise
    ports:
      - "5434:5432"
    volumes:
      - pg_profile_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: nutriwise-redis
    ports:
      - "6379:6379"

  kafka:
    image: apache/kafka:latest
    container_name: nutriwise-kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0

volumes:
  pg_auth_data:
  pg_profile_data:
